
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_URI: mongodb://host.docker.internal:27017/snake-game  # Cambiar localhost a host.docker.internal
    depends_on:
      #- prometheus
      - grafana

  #prometheus:
    #image: prom/prometheus
    #ports:
      #- "9090:9090"
    #volumes:
      #- ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

volumes:
  pgdata:
